<?php
$z[0]=Array("field","",50,79);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",85,116);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("channel","\r\n          <li class=\"proOne\"><a href=\"[field:typeurl/]\" class=\"\">[field:typename/]</a></li>\r\n        ",170,416);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['row']="5";
$z[2][4]['currentstyle']="<li class='proOne'><a href='~typelink~' class='thisclass'>~typename~</a> </li>";

?>