<?php
$z[0]=Array("field","",78,107);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",126,157);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",197,295);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['row']="6";
$z[3]=Array("arclist","\r\n      <li> <a href=\"[field:arcurl/]\" class=\"iproimg\"><font class=\"caseborder\"></font><img src=\"[field:picname/]\" width=\"300\" height=\"225\" >\r\n        <p>　[field:description function=\"cn_substr(@me,160)\"/]...</p>\r\n        </a> <a href=\"[field:arcurl/]\" class=\"iproname\">[field:title/]</a> </li>\r\n      ",318,684);
$z[3][4]=array();
$z[3][4]['titlelen']="80";
$z[3][4]['orderby']="id";
$z[3][4]['row']="6";
$z[4]=Array("field","",726,754);
$z[4][4]=array();
$z[4][4]['name']="typeurl";

?>