<?php
$z[0]=Array("field","",81,110);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",129,160);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("arclist","\r\n      <li> <a href=\"[field:arcurl/]\" class=\"proimg\"><img src=\"[field:picname/]\" width=\"300\" height=\"225\" ></a> <a href=\"[field:arcurl/]\" class=\"proname\"> [field:title/] </a> </li>\r\n      ",205,456);
$z[2][4]=array();
$z[2][4]['titlelen']="80";
$z[2][4]['orderby']="id";
$z[2][4]['row']="3";
$z[3]=Array("field","",498,526);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>