<?php
$z[0]=Array("field","",103,132);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n      <h2><a href=\"[field:arcurl/]\"> [field:title/] </a></h2>\r\n      <p class=\"title_intr\"> 　[field:description function=\"cn_substr(@me,120)\"/]... </p>\r\n      ",170,399);
$z[1][4]=array();
$z[1][4]['titlelen']="80";
$z[1][4]['orderby']="id";
$z[1][4]['limit']="0,1";
$z[2]=Array("arclist","\r\n        <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><span class=\"fl\"> [field:title/] </span><span class=\"fr\"> [field:pubdate function=\"MyDate('Y-m-d',@me)\"/] </span></a></li>\r\n        ",437,698);
$z[2][4]=array();
$z[2][4]['titlelen']="80";
$z[2][4]['orderby']="id";
$z[2][4]['limit']="1,3";
$z[3]=Array("field","",738,766);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>