<?php
$z[0]=Array("field","",51,80);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",86,117);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",133,161);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n          ",237,399);
$z[3][4]=array();
$z[3][4]['titlelen']="80";
$z[3][4]['orderby']="id";
$z[3][4]['row']="5";

?>