<?php
$z[0]=Array("arcurl","",14,29);
$z[0][4]=array();
$z[1]=Array("title","",38,52);
$z[1][4]=array();
$z[2]=Array("title","",71,85);
$z[2][4]=array();
$z[3]=Array("pubdate","",109,156);
$z[3][4]=array();
$z[3][4]['function']="MyDate('Y-m-d',@me)";
$z[4]=Array("global","\r\n        \$a=\"\r\n        <div class='news_line'></div>\r\n        \";\r\n        \$b=\"\";\r\n        if ((@me%5)==0 && @me!=30) @me=\$a;\r\n        else  @me=\$b;\r\n        ",183,398);
$z[4][4]=array();
$z[4][4]['runphp']="yes";
$z[4][4]['name']="autoindex";

?>