<?php
$z[0]=Array("flink","",130,152);
$z[0][4]=array();
$z[0][4]['row']="24";
$z[1]=Array("global","",207,229);
$z[1][4]=array();
$z[1][4]['name']="cfg_adr";
$z[2]=Array("global","",246,268);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",285,309);
$z[3][4]=array();
$z[3][4]['name']="cfg_phone";
$z[4]=Array("global","",336,362);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";

?>