<?php
$z[0]=Array("field","(@me==\"\")? @me=\" class='on' \":@me=\"\";",39,126);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channelartlist","\r\n    <li><a class=\"{dede:field.currentstyle/}\" href=\"{dede:field name='typeurl'/}\"> {dede:field name='typename'/} </a></li>\r\n    ",164,368);
$z[1][4]=array();
$z[1][4]['typeid']="top";
$z[1][4]['currentstyle']="on";
$z[2]=Array("global","",589,614);
$z[2][4]=array();
$z[2][4]['name']="cfg_ggtext";

?>