<?php
$z[0]=Array("channelartlist","\r\n      <div class=\"l_pro\">\r\n        <div class=\"l_title\">{dede:field name='typename'/}<font>{dede:field name='typenameen'/}</font></div>\r\n        <ul class=\"l_procon\">\r\n        {dede:channel type='son' row='5' currentstyle=\"<li class='proOne'><a href='~typelink~' class='thisclass'>~typename~</a> </li>\" }\r\n          <li class=\"proOne\"><a href=\"[field:typeurl/]\" class=\"\">[field:typename/]</a></li>\r\n        {/dede:channel} \r\n        </ul>\r\n      </div>\r\n      ",26,544);
$z[0][4]=array();
$z[0][4]['typeid']="4,0";
$z[1]=Array("channelartlist","\r\n      <div class=\"l_news\">\r\n        <div class=\"l_title\">{dede:field name='typename'/}<font>{dede:field name='typenameen'/}</font><a href=\"{dede:field name='typeurl'/}\" title=\"更多\">更多></a></div>\r\n        <ul class=\"pointer\">\r\n          {dede:arclist titlelen=80 orderby='id' row='5'}\r\n          <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n          {/dede:arclist}  \r\n        </ul>\r\n      </div>\r\n      ",552,1054);
$z[1][4]=array();
$z[1][4]['typeid']="2,0";
$z[2]=Array("global","",1247,1269);
$z[2][4]=array();
$z[2][4]['name']="cfg_adr";
$z[3]=Array("global","",1297,1319);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",1346,1368);
$z[4][4]=array();
$z[4][4]['name']="cfg_fax";

?>