<?php
$z[0]=Array("type","[field:typeurl/]",33,84);
$z[0][4]=array();
$z[0][4]['typeid']="10";
$z[1]=Array("global","",386,412);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",477,503);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",570,592);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",599,621);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";

?>